### PR TITLE
[COMPOSER] Switch phptree package as it changed its name and namespace

### PR DESCRIPTION
**Pull request by mfn**
Fixes https://github.com/fntneves/laravel-transactional-events/issues/35

Only the package was renamed, not the code/namespace

### CODE REVIEW

**Comment by drupol** [comment]
I will update the namespaces very soon, probably tomorow.

**Comment by mfn** [comment]
@drupol ok, waiting for your ping then!

**Comment by drupol** [comment]
@mfn Version 2.5.0 is now ready and tagged, you may update now.

**Comment by mfn** [comment]
@drupol all done, thx for the jeads up!

@fntneves StyleCI was updated the last time it ran on the repo so it complained which required me to add the noise to the PR => it's a separate (3rd) commit and purely to satisfy StyleCI, not my fault.

**Comment by drupol** [comment]
Great, so far so good :-)
Thanks for using my package guys !!!

**Comment by fntneves** [comment]
Will merge it today, thank you @mfn and @drupol for notifying.

**Comment by markokeeffe** [comment]
I can't figure out how, but after a composer update, I ended up with `loophp/phptree` version `2.5.0`.

This resulted in the following error:
```
Class 'drupol\phptree\Node\ValueNode' not found
```

My composer.json has `"fntneves/laravel-transactional-events": "^1.8"`

If I execute `composer why drupol/phptree` I get:
```
fntneves/laravel-transactional-events  1.8.4  requires  drupol/phptree (^2.3)
```

I had to specifically require version `2.3.2` of phptree in my project:
```
composer require drupol/phptree:2.3.2
```

Once this PR is merged I'm hoping I can remove the explicit requirement for `drupol/phptree:2.3.2` and update this package.

**Comment by mfn** [comment]
> I can't figure out how, but after a composer update, I ended up with `loophp/phptree` version `2.5.0`.

I've say this is an error of the (deprecated) drupol/phptree package => it should not offer a 2.5.0 with a wrong namespace.

Specifically, this release https://packagist.org/packages/drupol/phptree#2.5.0 should **not** be on this package

Ping @drupol

**Comment by fntneves** [comment]
> I can't figure out how, but after a composer update, I ended up with `loophp/phptree` version `2.5.0`.
> 
> This resulted in the following error:
> 
> ```
> Class 'drupol\phptree\Node\ValueNode' not found
> ```
> 
> My composer.json has `"fntneves/laravel-transactional-events": "^1.8"`
> 
> If I execute `composer why drupol/phptree` I get:
> 
> ```
> fntneves/laravel-transactional-events  1.8.4  requires  drupol/phptree (^2.3)
> ```
> 
> I had to specifically require version `2.3.2` of phptree in my project:
> 
> ```
> composer require drupol/phptree:2.3.2
> ```
> 
> Once this PR is merged I'm hoping I can remove the explicit requirement for `drupol/phptree:2.3.2` and update this package.

This should be fixed now. I've released 1.8.5 which includes this change.

**Comment by drupol** [comment]
Sorry for the mess guys... I hope everything is back in order. Let me know how I can help if needed.

**Pull request merged**
